### ISSUE TITLE
Library fails when account has no refunds

### ISSUE THREAD

**Issue by kodek** [starsprung/amazon-order-reports-api#15]
I'm trying to use the YNAB script, and it fails with the following error:

```
{"level":"info","message":"Retrieving reports from Amazon","metadata":{},"timestamp":"2021-01-05T02:26:13.784Z"}
(node:23752) UnhandledPromiseRejectionWarning: Error: Invalid Record Length: columns length is 18, got 1 on line 2
    at Parser.__onRow (C:\snapshot\amazon-ynab-sync\node_modules\csv-parse\lib\index.js:762:9)
    at Parser.__parse (C:\snapshot\amazon-ynab-sync\node_modules\csv-parse\lib\index.js:635:40)
    at Parser._flush (C:\snapshot\amazon-ynab-sync\node_modules\csv-parse\lib\index.js:453:22)
    at Parser.prefinish (_stream_transform.js:142:10)
    at Parser.emit (events.js:315:20)
    at prefinish (_stream_writable.js:618:14)
    at finishMaybe (_stream_writable.js:626:5)
    at Parser.Writable.end (_stream_writable.js:570:5)
    at ReadStream.onend (_stream_readable.js:677:10)
    at Object.onceWrapper (events.js:421:28)
```

Looking at my Amazon order history reports, the only reports generated by the library were of type Refund. This is what one of them looks like:

```
Order ID,Order Date,Title,Category,ASIN/ISBN,Website,Purchase Order Number,Refund Date,Refund Condition,Refund Amount,Refund Tax Amount,Tax Exemption Applied,Refund Reason,Quantity,Seller,Seller Credentials,Buyer Name,Group Name
No data found for this time period
```

**Comment by starsprung** [comment]
Fixed in v3.3.2

**Comment by starsprung** [comment]
This should now be fixed in https://github.com/starsprung/amazon-ynab-sync, I've updated it to the latest version of this library.

**Comment by kodek** [comment]
Awesome. Thanks!
