### ISSUE TITLE
Does not work for me (updated order report site?)

### ISSUE THREAD

**Issue by bvosk** [starsprung/amazon-order-reports-api#21]
First off, thank you for this awesome repo!

I'm trying to use this for YNAB sync along with your other repo - [`amazon-ynab-sync`](https://github.com/starsprung/amazon-ynab-sync). This is a better-thought out solution than my approach to the same problem of categorizing Amazon purchases in YNAB. However when I run it under my account, I get the following output:

```
{"level":"info","message":"Retrieving reports from Amazon","metadata":{},"timestamp":"2022-06-25T12:39:26.229Z"}
(node:34621) UnhandledPromiseRejectionWarning: Error: No sign-out link detected, failed to sign in?
    at AmazonOrderReportsApi._assert (/Users/brian/.nvm/versions/node/v14.17.1/lib/node_modules/amazon-ynab-sync/node_modules/amazon-order-reports-api/lib/index.js:198:19)
    at async AmazonOrderReportsApi._handleLogin (/Users/brian/.nvm/versions/node/v14.17.1/lib/node_modules/amazon-ynab-sync/node_modules/amazon-order-reports-api/lib/index.js:331:9)
    at async AmazonOrderReportsApi._navigate (/Users/brian/.nvm/versions/node/v14.17.1/lib/node_modules/amazon-ynab-sync/node_modules/amazon-order-reports-api/lib/index.js:360:9)
    at async AmazonOrderReportsApi._getReport (/Users/brian/.nvm/versions/node/v14.17.1/lib/node_modules/amazon-ynab-sync/node_modules/amazon-order-reports-api/lib/index.js:265:9)
    at async AmazonOrderReportsApi.getItems (/Users/brian/.nvm/versions/node/v14.17.1/lib/node_modules/amazon-ynab-sync/node_modules/amazon-order-reports-api/lib/index.js:124:9)
    at async Object.getAmazonTransactions (/Users/brian/.nvm/versions/node/v14.17.1/lib/node_modules/amazon-ynab-sync/lib/amazon.js:72:26)
    at async Object.batch [as default] (/Users/brian/.nvm/versions/node/v14.17.1/lib/node_modules/amazon-ynab-sync/node_modules/it-batch/index.js:20:20)
    at async /Users/brian/.nvm/versions/node/v14.17.1/lib/node_modules/amazon-ynab-sync/lib/index.js:21:22
(Use `node --trace-warnings ...` to show where the warning was created)
(node:34621) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:34621) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

When I run with the `--debug-mode` flag, I can see it get to the order reports screen. But then it gets stuck there. I'm assuming Amazon updated the order reports page and the selector needs to be updated.

Just wanted to open an issue and say that I'll be working on updates in a fork. Please let me know if you have any thoughts and if you are open to accepting a PR.

**Comment by helen8297** [comment]
Did that pr fix the issue? I want to use this package but don't know if its working to be worth the time!

**Comment by bvosk** [comment]
Yes it works for me!

**Comment by helen8297** [comment]
Thanks! Is it just for US accounts or business accounts? I tried doing it with my UK consumer account through the Amazon site and it didn’t work On 24 Sep 2022, at 16:50, Brian Voskerijian ***@***.***> wrote:﻿
Yes it works for me!
